import type { ArcBeatDef } from '../sim/types';

/**
 * Client arc beats — the narrative spine of a treatment.
 *
 * A beat is one glimpse of a real person's week, drawn when a session resolves
 * and shown on the reflect card and in the client's story feed. Beats are
 * keyed by chapter (Trust → Work → Consolidation), optionally by condition and
 * severity band, and carry a small mechanical nudge so the story and the
 * numbers always agree with each other.
 *
 * Authoring rules kept here on purpose:
 *  - stability  ±0.05 … 0.18
 *  - rapport    ±0.04 … 0.12
 *  - resilience  +0.03 … 0.10
 *  - progress   ±3 … 8
 *  - patience   ±5 … 15
 * Anything bigger belongs in an event, not a beat.
 *
 * Three beats hand off to full events instead of a silent nudge:
 * ev_client_crisis_call, ev_client_asks_to_end, ev_client_brings_partner.
 */
export const ARC_BEATS: readonly ArcBeatDef[] = [
  // ───────────────────────────────────────────────────────────────────────────
  // TRUST — is this room safe, and are you going to flinch?
  // ───────────────────────────────────────────────────────────────────────────

  {
    id: 'beat_first_tears',
    chapter: 'trust',
    text: 'It arrives mid-sentence, over something small: a broken kettle, a text nobody answered. They apologise for it twice, then let it happen.',
    weight: 3,
    effects: { rapport: 0.11, stability: 0.05, progress: 3 },
    mood: 'warm',
  },
  {
    id: 'beat_borrowed_problem',
    chapter: 'trust',
    text: "Fifty minutes on a friend's terrible marriage. At the door they concede it was, at least, a very good story.",
    weight: 4,
    effects: { progress: -4, rapport: 0.05, patience: 6 },
    mood: 'curious',
  },
  {
    id: 'beat_testing_the_frame',
    chapter: 'trust',
    text: 'Near the end they ask, lightly, whether people ever just stop coming. You say yes, it happens. They nod like they have been handed something.',
    weight: 3,
    effects: { rapport: 0.07, stability: 0.05, patience: 7 },
    mood: 'curious',
  },
  {
    id: 'beat_anxiety_parking_lot_early',
    chapter: 'trust',
    conditions: ['anxiety'],
    maxSeverity: 3,
    text: 'Reception mentions they have been in the car park since twenty past. Not on their phone. Just sitting, getting ready to come in.',
    weight: 4,
    effects: { patience: 9, rapport: 0.05, stability: 0.05 },
    mood: 'curious',
  },
  {
    id: 'beat_depression_showered_for_this',
    chapter: 'trust',
    conditions: ['depression'],
    text: 'They showered for this. It is offered like an apology; you take it like the news it is.',
    weight: 4,
    effects: { rapport: 0.08, progress: 4, patience: 8 },
    mood: 'warm',
  },
  {
    id: 'beat_trauma_edge_of_the_year',
    chapter: 'trust',
    conditions: ['trauma'],
    minSeverity: 3,
    text: 'They walk right up to the year they do not talk about, look at it, and change the subject. You let them. Twice is not a failure.',
    weight: 3,
    effects: { stability: 0.06, rapport: 0.06, progress: 3 },
    mood: 'tense',
  },
  {
    id: 'beat_grief_two_plates',
    chapter: 'trust',
    conditions: ['grief'],
    text: 'Four months on, they still lay two places at dinner. What they came to ask was whether that meant something was wrong with them. It does not.',
    weight: 4,
    effects: { rapport: 0.09, stability: 0.05 },
    mood: 'sad',
  },
  {
    id: 'beat_ocd_naming_the_rule',
    chapter: 'trust',
    conditions: ['ocd'],
    text: 'They describe the arrangement with the stove — three checks, always an odd number — and hear how it sounds out loud for the first time.',
    weight: 4,
    effects: { progress: 4, rapport: 0.06, stability: 0.05 },
    mood: 'curious',
  },
  {
    id: 'beat_substance_the_honest_number',
    chapter: 'trust',
    conditions: ['substance'],
    minSeverity: 3,
    text: 'Asked a second time, they revise the number upward. Six, not two. Nothing in the room changes, and they watch carefully to be sure.',
    weight: 3,
    effects: { rapport: 0.1, progress: 4, stability: 0.05 },
    mood: 'tense',
  },
  {
    id: 'beat_psychosis_two_explanations',
    chapter: 'trust',
    conditions: ['psychosis'],
    minSeverity: 2,
    text: "They hold two accounts of the neighbour's radio at once — theirs and the ordinary one — and agree, cautiously, to leave both on the table.",
    weight: 2,
    effects: { stability: 0.08, rapport: 0.07, progress: 3 },
    mood: 'curious',
  },
  {
    id: 'beat_behavioral_the_triceratops',
    chapter: 'trust',
    conditions: ['behavioral'],
    text: 'They negotiate hard for the plastic triceratops to stay in the room. Granted. The triceratops, it turns out, has a great deal to say about school.',
    weight: 4,
    effects: { rapport: 0.1, progress: 3, stability: 0.05, prefersModality: 'play' },
    mood: 'warm',
  },
  {
    id: 'beat_identity_the_name_first',
    chapter: 'trust',
    conditions: ['identity'],
    text: 'They try the name out in here before anywhere else, and ask you to use it for the hour. You do, and the hour goes differently.',
    weight: 3,
    effects: { rapport: 0.11, stability: 0.06, progress: 4 },
    mood: 'warm',
  },
  {
    id: 'beat_relationship_the_we',
    chapter: 'trust',
    conditions: ['relationship'],
    text: 'Every sentence begins with we. Asked what they want on their own, they go quiet for a long and useful minute.',
    weight: 4,
    effects: { progress: 3, rapport: 0.05, stability: 0.05 },
    mood: 'curious',
  },
  {
    id: 'beat_burnout_status_update',
    chapter: 'trust',
    conditions: ['burnout'],
    maxSeverity: 3,
    text: 'They arrive from a meeting that ran long, laptop still under one arm. Asked how they are, they deliver a status update.',
    weight: 4,
    effects: { progress: 3, rapport: 0.05, patience: -6 },
    mood: 'curious',
  },

  // ───────────────────────────────────────────────────────────────────────────
  // WORK — the middle, where life keeps happening on top of the treatment
  // ───────────────────────────────────────────────────────────────────────────

  {
    id: 'beat_setback_week',
    chapter: 'work',
    minSeverity: 2,
    text: 'One bad week undoes a good month, or seems to. They sit down heavy and say they are back at the start, and they mean it.',
    weight: 3,
    effects: { stability: -0.13, patience: -11, progress: -4 },
    mood: 'sad',
  },
  {
    id: 'beat_asks_for_a_different_door',
    chapter: 'work',
    text: 'They have been reading about something else. Not that this is not helping, they add quickly — which is how people ask for what they need.',
    weight: 3,
    effects: { progress: -3, rapport: 0.05, patience: -6, prefersModality: 'somatic' },
    mood: 'curious',
  },
  {
    id: 'beat_the_new_job',
    chapter: 'work',
    text: 'A promotion, and with it a commute that eats the Tuesday slot. They ask, carefully, whether the work survives being rescheduled.',
    weight: 3,
    effects: { patience: -8, progress: 3, stability: -0.06 },
    mood: 'curious',
  },
  {
    id: 'beat_the_move_across_town',
    chapter: 'work',
    text: 'Boxes in the hallway, a lease signed on the other side of town. They are delighted about it, and they are not sleeping.',
    weight: 3,
    effects: { stability: -0.07, patience: -7, progress: 3 },
    mood: 'curious',
  },
  {
    id: 'beat_a_death_on_a_sunday',
    chapter: 'work',
    text: 'Their aunt died on a Sunday. They came in anyway and spent the hour apologising for talking about something other than what they came for.',
    weight: 2,
    effects: { stability: -0.1, rapport: 0.08, patience: -5, addComorbidity: 'grief' },
    mood: 'sad',
  },
  {
    id: 'beat_after_hours_call',
    chapter: 'work',
    minSeverity: 4,
    text: 'The phone goes at ten past nine, long after the last door was locked, and it is them.',
    weight: 1,
    event: 'ev_client_crisis_call',
    mood: 'tense',
  },
  {
    id: 'beat_asks_to_bring_someone',
    chapter: 'work',
    text: 'They ask whether the person they live with could come along once. Apparently the question at home is always the same: what do you two actually do in there?',
    weight: 2,
    event: 'ev_client_brings_partner',
    mood: 'curious',
  },
  {
    id: 'beat_the_flat_stretch',
    chapter: 'work',
    text: 'Nothing happened this week. Nothing happened last week either. They want to know whether that means it is working or finished.',
    weight: 4,
    effects: { progress: -3, patience: -7, resilience: 0.04 },
    mood: 'curious',
  },
  {
    id: 'beat_anxiety_rode_it_out',
    chapter: 'work',
    conditions: ['anxiety'],
    text: 'Eleven minutes in the supermarket queue, all of them awful, none of them abandoned. They timed it, which is very them.',
    weight: 4,
    effects: { resilience: 0.07, progress: 5, stability: 0.06 },
    mood: 'proud',
  },
  {
    id: 'beat_depression_three_walks',
    chapter: 'work',
    conditions: ['depression'],
    text: 'Three walks this week instead of one. They report it flatly, as data, and seem faintly annoyed that it helped.',
    weight: 4,
    effects: { progress: 5, resilience: 0.05, stability: 0.06 },
    mood: 'warm',
  },
  {
    id: 'beat_trauma_asks_about_emdr',
    chapter: 'work',
    conditions: ['trauma'],
    minSeverity: 3,
    text: 'Someone in their group mentioned the eye-movement thing. They want to know whether it is real, and whether it is faster.',
    weight: 2,
    effects: { rapport: 0.06, progress: 3, prefersModality: 'emdr' },
    mood: 'curious',
  },
  {
    id: 'beat_ocd_left_it_unchecked',
    chapter: 'work',
    conditions: ['ocd'],
    text: 'The stove got checked once. They drove to work with both hands tight on the wheel and did not turn the car around.',
    weight: 3,
    effects: { resilience: 0.08, progress: 6, stability: 0.05 },
    mood: 'proud',
  },
  {
    id: 'beat_adhd_the_system_that_stuck',
    chapter: 'work',
    conditions: ['adhd'],
    text: 'The fourth system is the one that stuck: a whiteboard by the door, three things on it, nothing else allowed. Two weeks in and it is still there.',
    weight: 4,
    effects: { resilience: 0.07, progress: 5, patience: 8 },
    mood: 'proud',
  },
  {
    id: 'beat_substance_the_slip',
    chapter: 'work',
    conditions: ['substance'],
    minSeverity: 3,
    text: 'Friday went badly. They came in on Monday and told you before you asked, which is not nothing — it is most of it.',
    weight: 3,
    effects: { stability: -0.11, progress: -4, rapport: 0.06, patience: -6 },
    mood: 'tense',
  },
  {
    id: 'beat_eating_the_meal_out',
    chapter: 'work',
    conditions: ['eating'],
    minSeverity: 3,
    text: 'Dinner with friends, and a menu they had not read in advance. They ordered, ate some of it, and stayed at the table through the coffee.',
    weight: 3,
    effects: { stability: -0.06, progress: 5, resilience: 0.06, rapport: 0.05 },
    mood: 'tense',
  },
  {
    id: 'beat_bipolar_watching_the_sleep',
    chapter: 'work',
    conditions: ['bipolar'],
    minSeverity: 3,
    text: 'They have started logging sleep, because both times it went sideways it began the same way: four good nights of not needing any.',
    weight: 3,
    effects: { resilience: 0.08, stability: 0.07, progress: 4 },
    mood: 'curious',
  },

  // ───────────────────────────────────────────────────────────────────────────
  // CONSOLIDATION — making it portable, and learning how to leave
  // ───────────────────────────────────────────────────────────────────────────

  {
    id: 'beat_asks_how_people_know',
    chapter: 'consolidation',
    text: 'Near the end, sideways, half to the window: how do people know when they are finished with this?',
    weight: 2,
    event: 'ev_client_asks_to_end',
    mood: 'curious',
  },
  {
    id: 'beat_grief_a_whole_thursday',
    chapter: 'consolidation',
    conditions: ['grief'],
    text: 'They got a whole Thursday without it, and then felt guilty about the Thursday. Both of those are allowed in here.',
    weight: 3,
    effects: { resilience: 0.07, stability: 0.08, progress: 5 },
    mood: 'warm',
  },
  {
    id: 'beat_adhd_teaches_the_trick',
    chapter: 'consolidation',
    conditions: ['adhd'],
    text: "They taught the whiteboard trick to a colleague who was drowning, and got to watch someone else's face do what theirs did.",
    weight: 3,
    effects: { resilience: 0.06, progress: 5, rapport: 0.06 },
    mood: 'proud',
  },
  {
    id: 'beat_relationship_twenty_minutes',
    chapter: 'consolidation',
    conditions: ['relationship'],
    text: 'An argument on Sunday that finished in twenty minutes instead of three days. Nobody slept on the sofa. They report it like a score line.',
    weight: 3,
    effects: { progress: 6, resilience: 0.06, stability: 0.06 },
    mood: 'proud',
  },
  {
    id: 'beat_eating_the_hallway_mirror',
    chapter: 'consolidation',
    conditions: ['eating'],
    text: 'The mirror in the hallway is mostly just a mirror now. Mostly is the word they keep, and they are right to keep it.',
    weight: 3,
    effects: { stability: 0.07, resilience: 0.06, progress: 5 },
    mood: 'warm',
  },
  {
    id: 'beat_bipolar_the_plan_on_the_fridge',
    chapter: 'consolidation',
    conditions: ['bipolar'],
    text: 'The plan lives on the fridge and two people hold copies: what to watch for, who to ring, what not to buy. Their sister asked to be one of them.',
    weight: 3,
    effects: { resilience: 0.08, stability: 0.07, progress: 5 },
    mood: 'proud',
  },
  {
    id: 'beat_burnout_said_no_in_writing',
    chapter: 'consolidation',
    conditions: ['burnout'],
    text: 'They said no to a project on Tuesday, in writing, and then waited an hour for the sky to come down. It stayed up.',
    weight: 4,
    effects: { resilience: 0.08, progress: 6, stability: 0.06 },
    mood: 'proud',
  },
  {
    id: 'beat_behavioral_the_teachers_email',
    chapter: 'consolidation',
    conditions: ['behavioral'],
    text: 'An unprompted email from the teacher about a good fortnight. It was read out twice in the waiting room, the second time for the receptionist.',
    weight: 3,
    effects: { progress: 6, rapport: 0.06, stability: 0.06 },
    mood: 'warm',
  },
  {
    id: 'beat_identity_the_dinner_table',
    chapter: 'consolidation',
    conditions: ['identity'],
    text: 'They told the table, and the table went quiet, and then it did not stay quiet. Two of the four have rung since.',
    weight: 2,
    effects: { rapport: 0.08, resilience: 0.07, progress: 5 },
    mood: 'warm',
  },
  {
    id: 'beat_depression_moved_the_furniture',
    chapter: 'consolidation',
    conditions: ['depression'],
    text: 'They rearranged the living room. No theory anywhere says that means anything. It means something.',
    weight: 3,
    effects: { progress: 5, stability: 0.07, resilience: 0.05 },
    mood: 'warm',
  },
  {
    id: 'beat_trauma_the_whole_year',
    chapter: 'consolidation',
    conditions: ['trauma'],
    minSeverity: 3,
    text: 'They tell the year, start to finish, in ordinary sentences. When it ends the room is just a room and the clock is just late.',
    weight: 2,
    effects: { progress: 7, resilience: 0.09, stability: 0.06, rapport: 0.07 },
    mood: 'proud',
  },
  {
    id: 'beat_psychosis_two_modules',
    chapter: 'consolidation',
    conditions: ['psychosis'],
    text: 'Two modules, part-time, starting in September. The plan includes what to do if it goes badly, which is why you believe it.',
    weight: 2,
    effects: { progress: 6, stability: 0.08, resilience: 0.07 },
    mood: 'warm',
  },
];
