import type { GameEventDef } from '../sim/types';

/**
 * Staff, practice and program events — the life of the institution.
 *
 * Staff events are about therapists as people; practice events are about the
 * building, the money and the paperwork; program events are one flavoured
 * dilemma per running program.
 *
 * House rules: 2–4 choices, every hint honest about what it costs, modest
 * magnitudes, no hidden punishments.
 */
export const PRACTICE_EVENTS: readonly GameEventDef[] = [
  // ───────────────────────────────────────────────────────────────────────────
  // STAFF — therapists as people
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: 'ev_staff_corner_office',
    scope: 'staff',
    title: 'The Corner Office',
    body: "The room with two windows came free this morning. {therapist} has already measured it for a reading chair, and someone else has been quietly walking their plants past the door. Nobody has said anything unkind yet. That is exactly why you should decide before they do.",
    weight: 6,
    mood: 'tense',
    minDay: 18,
    requires: { minTherapists: 2 },
    choices: [
      {
        id: 'give_to_therapist',
        label: 'Give the room to {therapist}',
        hint: 'They are delighted. The other one hears about it within the hour.',
        effects: {
          therapistMorale: 8,
          allMorale: -2,
          log: '{therapist} moved into the corner office. The reading chair arrived by Thursday.',
        },
        outcome: 'They carry the chair up themselves and refuse all offers of help.',
      },
      {
        id: 'draw_for_it',
        label: 'Draw for it, in the open, over coffee',
        hint: 'Nobody gets an advantage, and everyone watches nobody get one.',
        effects: {
          allMorale: 3,
          log: 'The corner office went to a folded slip of paper in front of witnesses.',
        },
        outcome: 'The loser is gracious in a way that costs them visible effort, and gets credit for it.',
      },
      {
        id: 'shared_consult_room',
        label: 'Make it a shared consult room instead',
        hint: '-$180 to furnish it. Nobody wins, and the practice gains a quiet room.',
        effects: {
          cash: -180,
          allMorale: 2,
          setFlag: 'consult_room',
          log: 'The corner room became a shared consult space. Two chairs, one lamp, a door that locks.',
        },
      },
    ],
  },
  {
    id: 'ev_staff_supervisee_outgrows_mentor',
    scope: 'staff',
    title: 'Outgrown',
    body: "{therapist} arrived needing a supervisor for every third question. This week they ran a session you could not have run better. Their mentor still books the Thursday hour, and still calls it teaching.",
    weight: 5,
    mood: 'curious',
    minDay: 30,
    requires: { minTherapists: 2 },
    choices: [
      {
        id: 'graduate_them',
        label: 'End the pairing, warmly and out loud',
        hint: 'A real milestone for {therapist}. Their mentor gets a Thursday-shaped hole.',
        effects: {
          therapistMorale: 9,
          therapistXp: 80,
          allMorale: -2,
          xp: 40,
          log: '{therapist} graduated out of supervision.',
        },
      },
      {
        id: 'peer_consultation',
        label: 'Rewrite the hour as peer consultation',
        hint: 'Both keep the time. Neither of them is the student any more.',
        effects: {
          therapistMorale: 5,
          allMorale: 2,
          xp: 25,
          setFlag: 'peer_consult_hour',
        },
        outcome: 'By the third week they are arguing about a case as equals, which is the point.',
      },
      {
        id: 'say_nothing',
        label: 'Leave it alone for now',
        hint: 'Nothing breaks today. {therapist} notices that you noticed nothing.',
        effects: { therapistMorale: -5 },
      },
    ],
  },
  {
    id: 'ev_staff_rival_flowers',
    scope: 'staff',
    title: 'Flowers, No Occasion',
    body: "A courier leaves a bouquet at reception: eucalyptus, ranunculus, and a card with a first name and a mobile number on it. Everyone pretends not to read the card. {therapist} puts the stems in water anyway, which tells you they have not decided anything yet.",
    weight: 5,
    mood: 'tense',
    minDay: 22,
    choices: [
      {
        id: 'talk_plainly',
        label: 'Ask them straight what they want from the next year',
        hint: 'Costs one honest conversation. Usually worth more than money.',
        effects: {
          therapistMorale: 7,
          setFlag: 'staff_retention_talk',
          log: 'You and {therapist} spent forty minutes on what the next year should look like.',
        },
        outcome: 'They want two things. One of them is free.',
      },
      {
        id: 'preempt_raise',
        label: 'Offer a raise before they have to ask',
        hint: '-$900 now. Buys loyalty, and the others will hear the number.',
        effects: { cash: -900, therapistMorale: 10, allMorale: -2 },
      },
      {
        id: 'let_it_be_flowers',
        label: 'Let it be flowers',
        hint: 'No cost today. If they were wavering, they are still wavering.',
        effects: { therapistMorale: -3 },
      },
    ],
  },
  {
    id: 'ev_staff_four_day_week',
    scope: 'staff',
    title: 'Four Days',
    body: "{therapist} asks for ten minutes at the end of the day and spends eight of them apologising. The ask underneath is plain: four days a week, less money, one weekday that belongs to them.",
    weight: 6,
    mood: 'warm',
    minDay: 20,
    choices: [
      {
        id: 'yes_rebuild',
        label: 'Yes. Rebuild the week around it',
        hint: '+$200 of payroll saved, one less clinical day. They will not forget this.',
        effects: {
          cash: 200,
          therapistMorale: 12,
          allMorale: 2,
          log: '{therapist} dropped to four days. Wednesdays are theirs now.',
        },
        outcome: 'Two months later they tell you the Wednesday is what keeps the other four good.',
      },
      {
        id: 'trial_quarter',
        label: 'Trial it for one quarter and review honestly',
        hint: 'An honest hedge. They will take it, with one eyebrow raised.',
        effects: { therapistMorale: 6, setFlag: 'four_day_trial' },
      },
      {
        id: 'not_now',
        label: 'Not yet — and say exactly why',
        hint: 'Keeps the capacity. Costs trust, and you will be asked again.',
        effects: { therapistMorale: -8, allMorale: -2 },
      },
    ],
  },
  {
    id: 'ev_staff_specialisation_ask',
    scope: 'staff',
    title: 'A Course in the Spring',
    body: "{therapist} has a certification prospectus folded into quarters in their coat pocket, which means they have been carrying it around for a while. It costs real money and takes them off the floor for a week.",
    weight: 6,
    mood: 'curious',
    minDay: 20,
    choices: [
      {
        id: 'fund_full',
        label: 'Fund the whole thing',
        hint: '-$1200 and a thin week. They come back a different clinician.',
        requires: { minCash: 1400 },
        effects: {
          cash: -1200,
          therapistMorale: 12,
          therapistXp: 140,
          allMorale: 2,
          log: '{therapist} is booked onto the certification course.',
        },
      },
      {
        id: 'split_cost',
        label: 'Split the cost with them',
        hint: '-$500. Cheaper for you, and they own a piece of it.',
        effects: { cash: -500, therapistMorale: 6, therapistXp: 70 },
      },
      {
        id: 'ask_them_to_wait',
        label: 'Ask them to wait for a quieter quarter',
        hint: 'No cost. The prospectus goes back in the pocket.',
        effects: { therapistMorale: -6 },
      },
    ],
  },
  {
    id: 'ev_staff_quiet_struggle',
    scope: 'staff',
    title: 'The Quiet One',
    body: "{therapist}'s notes are still immaculate and their clients still turn up. But they have stopped eating lunch with anybody, and today they walked the long way past your door twice without knocking.",
    weight: 7,
    mood: 'sad',
    minDay: 16,
    choices: [
      {
        id: 'knock_first',
        label: 'Knock on their door instead',
        hint: 'Ten minutes now. Cheaper than a sabbatical in three weeks.',
        effects: {
          therapistMorale: 8,
          therapistEnergy: 12,
          log: 'You caught {therapist} before it got worse. They talked for most of an hour.',
        },
        outcome: 'It takes them four minutes to get past "I am fine" and then it comes out all at once.',
      },
      {
        id: 'lighten_book',
        label: 'Quietly take two clients off their book',
        hint: '-$150 of billing. They may be grateful, or they may be ashamed.',
        effects: { cash: -150, therapistMorale: 5, therapistEnergy: 18 },
      },
      {
        id: 'give_them_room',
        label: 'Give them room to come to you',
        hint: 'Sometimes right. Sometimes it is the sabbatical.',
        effects: { therapistMorale: -6 },
      },
    ],
  },
  {
    id: 'ev_staff_conference_invite',
    scope: 'staff',
    title: 'Three Days in a Cold City',
    body: "The regional conference wants {therapist} on a panel about waitlists and who gets seen. It is three days of their caseload landing on everybody else, a hotel bill, and a lanyard they will keep in a drawer for years.",
    weight: 5,
    mood: 'proud',
    minDay: 25,
    choices: [
      {
        id: 'send_them',
        label: 'Send them, hotel and all',
        hint: '-$700 and three thin days. Your name gets said in a room full of referrers.',
        effects: {
          cash: -700,
          reputation: 4,
          therapistMorale: 9,
          allMorale: -2,
          log: '{therapist} is on the conference panel. Somebody has to cover Thursday.',
        },
      },
      {
        id: 'panel_day_only',
        label: 'Send them for the panel day only',
        hint: '-$250 and one thin day. Half the shine, most of the point.',
        effects: { cash: -250, reputation: 2, therapistMorale: 5 },
      },
      {
        id: 'decline_conference',
        label: 'Decline — the schedule cannot take it',
        hint: 'Free. Somebody else takes the panel and the introductions.',
        effects: { therapistMorale: -5 },
      },
    ],
  },
  {
    id: 'ev_staff_first_cure',
    scope: 'staff',
    title: 'Their First',
    body: "{therapist} closed a case today — properly closed it, last session, the client crying in the good way at the door. They are standing in the kitchen not entirely sure what to do with their hands.",
    weight: 5,
    mood: 'proud',
    choices: [
      {
        id: 'mark_it',
        label: 'Stop everything for ten minutes and mark it',
        hint: 'Ten minutes of everybody\'s afternoon. Worth every one of them.',
        effects: {
          therapistMorale: 10,
          allMorale: 4,
          xp: 40,
          log: 'The whole practice stopped for ten minutes for {therapist}.',
        },
        outcome: 'Somebody finds candles. Nobody can find a lighter. It is perfect anyway.',
      },
      {
        id: 'private_note',
        label: 'Leave a note in their pigeonhole',
        hint: 'Quieter. For some people it lands twice as hard.',
        effects: { therapistMorale: 8 },
      },
      {
        id: 'debrief_the_work',
        label: 'Sit down and go through what actually worked',
        hint: 'Less confetti, more craft. They will do it again sooner.',
        effects: { therapistMorale: 5, therapistXp: 110, xp: 25 },
      },
    ],
  },
  {
    id: 'ev_staff_supervision_role',
    scope: 'staff',
    title: 'The Thursday Proposal',
    body: "{therapist} has carried a full book for eleven years and is not tired of the work — only of doing all of it alone at the front of the room. They would like to trade four client hours a week for supervising the juniors.",
    weight: 5,
    mood: 'curious',
    minDay: 35,
    requires: { minTherapists: 3 },
    choices: [
      {
        id: 'accept_supervision',
        label: 'Accept. Build the supervision hour into the week',
        hint: '-$200 of billed hours. Juniors grow faster and the floor gets calmer.',
        effects: {
          cash: -200,
          therapistMorale: 11,
          allMorale: 4,
          xp: 45,
          setFlag: 'supervision_hour',
          log: '{therapist} took on supervision. Thursdays are for the juniors now.',
        },
      },
      {
        id: 'half_measure',
        label: 'Two hours, not four',
        hint: 'A compromise nobody loves and nobody resents.',
        effects: { therapistMorale: 5, allMorale: 2 },
      },
      {
        id: 'decline_supervision',
        label: 'Not while the waitlist looks like that',
        hint: 'Keeps the hours on the board. They will ask again, or they will stop asking.',
        effects: { therapistMorale: -9 },
      },
    ],
  },
  {
    id: 'ev_staff_satellite_clinic',
    scope: 'staff',
    title: 'A Second Lamp',
    body: "There is an empty dental surgery on the north side with good light, a bus stop outside, and a rent that is almost reasonable. {therapist} has walked past it four times and drawn the waiting room on the back of an intake form.",
    weight: 3,
    once: true,
    mood: 'proud',
    minDay: 60,
    requires: { minPracticeLevel: 5 },
    choices: [
      {
        id: 'back_the_satellite',
        label: 'Back it. Your name over their door',
        hint: '-$1500 and you lose them from the floor. The practice becomes a place that makes places.',
        requires: { minCash: 1600 },
        effects: {
          cash: -1500,
          reputation: 6,
          communityTrust: 6,
          therapistMorale: 12,
          allMorale: 3,
          setFlag: 'satellite_clinic',
          log: 'A second clinic opens on the north side, run by {therapist}.',
        },
        outcome: 'They send a photograph of the first lamp lit, taken from the pavement outside.',
      },
      {
        id: 'plan_with_a_date',
        label: 'Not yet — but put a real date on it, in writing',
        hint: 'Costs nothing today. Keeps them, and keeps the drawing on the wall.',
        effects: { therapistMorale: 6, allMorale: 2, setFlag: 'satellite_planned' },
      },
      {
        id: 'ask_them_to_stay',
        label: 'Ask them to stay',
        hint: 'Honest, and it lands as a no. They will hear it as one.',
        effects: { therapistMorale: -10, allMorale: -2 },
      },
    ],
  },
  {
    id: 'ev_staff_night_owl_hours',
    scope: 'staff',
    title: 'Eight A.M. Is a Theory',
    body: "{therapist} does their best work after four, when the building goes quiet and the lamps take over the lighting. Before ten they are a kind, slow fog. Reception has started guarding the morning slots without being asked to.",
    weight: 5,
    mood: 'curious',
    requires: { therapistTrait: ['trait_night_owl'] },
    choices: [
      {
        id: 'formalise_evenings',
        label: 'Give them the late block, formally',
        hint: 'Their sessions get better. Somebody else inherits the eight o\'clocks.',
        effects: {
          therapistMorale: 8,
          allMorale: -2,
          setFlag: 'late_block',
          log: '{therapist} now owns the evening slots. Reception stopped improvising.',
        },
      },
      {
        id: 'better_kettle',
        label: 'Leave the rota alone and buy a better kettle',
        hint: '-$120. Small, faintly ridiculous, weirdly effective.',
        effects: { cash: -120, therapistMorale: 5, allMorale: 2 },
        outcome: 'The kettle becomes the most discussed object in the building for a fortnight.',
      },
      {
        id: 'hold_the_line',
        label: 'Ask them to hold the standard hours like everyone else',
        hint: 'Fair on paper. The mornings stay foggy.',
        effects: { therapistMorale: -6, allMorale: 2 },
      },
    ],
  },
  {
    id: 'ev_staff_perfectionist_notes',
    scope: 'staff',
    title: 'Version Nine',
    body: "{therapist}'s formulation for one client is now eleven pages and has been rewritten twice this week. It is genuinely excellent. It is also eleven pages, and the lights in their room were on at nine last night.",
    weight: 5,
    mood: 'curious',
    requires: { therapistTrait: ['trait_perfectionist'] },
    choices: [
      {
        id: 'cap_the_format',
        label: 'Set a two-page ceiling on formulations',
        hint: 'Gives them their evenings back. Feels, to them, like being asked to do worse work.',
        effects: { therapistEnergy: 18, therapistMorale: -4, allMorale: 2 },
      },
      {
        id: 'teach_the_format',
        label: 'Have them teach the format to everybody else',
        hint: 'Costs a supervision slot. The effort stops being spent on one folder.',
        effects: {
          therapistMorale: 8,
          allMorale: 3,
          xp: 35,
          log: '{therapist} taught the house formulation format. It is now four pages and better.',
        },
      },
      {
        id: 'let_them_cook',
        label: 'Let them cook',
        hint: 'Superb notes. Expensive evenings, paid in energy.',
        effects: { therapistEnergy: -12, therapistMorale: 4 },
      },
    ],
  },
  {
    id: 'ev_staff_paperwork_drawer',
    scope: 'staff',
    title: 'The Drawer',
    body: "Third drawer down, {therapist}'s desk: six weeks of unsigned progress notes, two unbilled claims, and a birthday card for somebody whose birthday was in March. The clinical work is faultless. The drawer is not.",
    weight: 5,
    mood: 'curious',
    requires: { therapistTrait: ['trait_paperwork_averse'] },
    choices: [
      {
        id: 'admin_afternoon',
        label: 'Buy them a whole admin afternoon',
        hint: 'Costs an afternoon of sessions, recovers the unbilled claims. Net +$550.',
        effects: {
          cash: 550,
          therapistMorale: 5,
          therapistEnergy: -10,
          log: 'The drawer was emptied. Two claims went out the same day.',
        },
      },
      {
        id: 'pair_with_reception',
        label: 'Pair them with reception for twenty minutes a day',
        hint: '-$150 of somebody else\'s week. The drawer stops growing.',
        effects: { cash: -150, therapistMorale: 7, allMorale: -2, setFlag: 'admin_buddy' },
      },
      {
        id: 'leave_the_drawer',
        label: 'Leave the drawer',
        hint: '-$300 in claims that time out. It compounds. It always compounds.',
        effects: { cash: -300, therapistMorale: -3 },
      },
    ],
  },
  {
    id: 'ev_staff_dual_relationship',
    scope: 'staff',
    title: 'A Name They Know',
    body: "{therapist} reads the new referral twice and then closes the folder. The client is the sister of somebody they stand next to at a football pitch every Sunday. Nobody has done anything wrong yet, which is precisely the moment to decide.",
    weight: 4,
    mood: 'tense',
    minDay: 22,
    requires: { minTherapists: 2 },
    choices: [
      {
        id: 'reassign_inhouse',
        label: 'Reassign the case to somebody else here',
        hint: 'Clean. Costs a scheduling headache and nothing else.',
        effects: { therapistMorale: 6, allMorale: 2, reputation: 1 },
      },
      {
        id: 'refer_across_town',
        label: 'Refer her to a colleague across town',
        hint: '-$400 of fees. The safest room is sometimes in another building.',
        effects: {
          cash: -400,
          communityTrust: 4,
          reputation: 2,
          therapistMorale: 4,
          log: 'The referral went across town. {therapist} wrote the handover themselves.',
        },
      },
      {
        id: 'proceed_with_boundaries',
        label: 'Proceed, with explicit boundaries and weekly supervision',
        hint: '+$250 of fees kept, and a risk you will have to keep watching every week.',
        effects: { cash: 250, therapistMorale: -4, setFlag: 'dual_relationship_open' },
      },
    ],
  },

  // ───────────────────────────────────────────────────────────────────────────
  // PRACTICE — the institution
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: 'ev_practice_insurance_renegotiation',
    scope: 'practice',
    title: 'The Renegotiation Window',
    body: "The panel contract for {practice} renews on the fifteenth. Their opening letter uses the word efficiencies twice and the word care once. You have three weeks and roughly one afternoon of actual leverage.",
    weight: 5,
    mood: 'tense',
    minDay: 30,
    choices: [
      {
        id: 'push_rates',
        label: 'Push hard on the rate',
        hint: '+$800 over the quarter. They meet you partway and add three new forms.',
        effects: {
          cash: 800,
          allMorale: -2,
          log: 'The panel moved on rate. Everyone now files a fourth form nobody reads.',
        },
      },
      {
        id: 'trade_for_volume',
        label: 'Trade rate for guaranteed referral volume',
        hint: '-$200 on margin, and a steadier flow through the door.',
        effects: {
          cash: -200,
          communityTrust: 2,
          spawnReferral: { severityBias: -0.2 },
          setFlag: 'volume_contract',
        },
      },
      {
        id: 'sign_as_is',
        label: 'Sign it as it stands and get back to work',
        hint: 'No fight, no gain, and the afternoon belongs to your clients.',
        effects: { allMorale: 2 },
      },
      {
        id: 'leave_the_panel',
        label: 'Leave the panel and go mostly self-pay',
        hint: '-$700 in the transition and fewer low-cost slots. A real bet on your name.',
        requires: { minReputation: 45 },
        effects: {
          cash: -700,
          reputation: 3,
          communityTrust: -5,
          setFlag: 'off_panel',
          log: '{practice} came off the insurance panel.',
        },
      },
    ],
  },
  {
    id: 'ev_practice_rent_increase',
    scope: 'practice',
    title: 'A Letter From the Landlord',
    body: "Eleven per cent, effective next quarter, set in a font that suggests this is not a conversation. The radiator in the second room, which has never once worked, does not appear anywhere in the letter.",
    weight: 6,
    mood: 'tense',
    minDay: 25,
    choices: [
      {
        id: 'just_pay',
        label: 'Pay it and say nothing',
        hint: '-$700 this quarter. The rooms stay the rooms.',
        effects: { cash: -700, allMorale: -2 },
      },
      {
        id: 'longer_lease',
        label: 'Negotiate — offer a longer lease for a smaller rise',
        hint: '-$300 instead, and you are tied to this building for two years.',
        effects: { cash: -300, setFlag: 'long_lease' },
      },
      {
        id: 'repairs_in_the_deal',
        label: 'Accept, but make the repairs part of the deal',
        hint: '-$550 and the radiator finally works. Warmer building, warmer staff.',
        effects: {
          cash: -550,
          allMorale: 3,
          log: 'The second room has heat for the first time. Somebody applauded.',
        },
      },
    ],
  },
  {
    id: 'ev_practice_accreditation_prep',
    scope: 'practice',
    title: 'Before the Site Visit',
    body: "The accreditation body sends a checklist forty pages long, eleven of which are about how you store paper. The visit is real and the reviewers are people. {practice} is closer to ready than the checklist makes it feel.",
    weight: 4,
    once: true,
    mood: 'curious',
    minDay: 45,
    requires: { minPracticeLevel: 4 },
    choices: [
      {
        id: 'full_prep',
        label: 'Two full days of preparation, everybody in',
        hint: '-$800 and two thin clinic days. You walk in knowing where everything is.',
        requires: { minCash: 950 },
        effects: {
          cash: -800,
          reputation: 5,
          allMorale: -2,
          setFlag: 'accred_prepped',
          log: '{practice} spent two days getting ready. The consent file is now a thing of beauty.',
        },
      },
      {
        id: 'targeted_prep',
        label: 'Fix the records and the consent forms, nothing else',
        hint: '-$300. Covers the two things that actually fail people.',
        effects: { cash: -300, reputation: 2, setFlag: 'accred_prepped' },
      },
      {
        id: 'trust_the_work',
        label: 'Trust the work to speak for itself',
        hint: 'Free. Reviewers grade the folder as well as the room.',
        effects: { reputation: -2, allMorale: 2 },
      },
    ],
  },
  {
    id: 'ev_practice_local_paper',
    scope: 'practice',
    title: 'The Paper Would Like a Photo',
    body: "A reporter from the local weekly wants eight hundred words on {practice} and a picture of the waiting room. She is polite, genuinely curious, and has already asked twice whether she might sit in on a session.",
    weight: 5,
    mood: 'curious',
    minDay: 20,
    choices: [
      {
        id: 'staff_and_rooms_only',
        label: 'Yes — staff and rooms, no clients, no exceptions',
        hint: 'She writes it either way. Better with you in it and the door shut.',
        effects: {
          reputation: 4,
          communityTrust: 5,
          log: 'The weekly ran eight hundred warm words about {practice} and a photo of the good lamp.',
        },
      },
      {
        id: 'ask_an_alumnus',
        label: 'Ask an alumnus whether they would like to speak, freely',
        hint: 'A bigger story, if and only if the yes is genuinely free to be a no.',
        effects: {
          reputation: 5,
          communityTrust: 6,
          allMorale: 2,
          setFlag: 'press_alum_story',
        },
        outcome: 'He asks for two changes before it runs. You make both without arguing.',
      },
      {
        id: 'decline_warmly',
        label: 'Decline, warmly, and offer her a coffee anyway',
        hint: 'No coverage. Also no chance of a client seeing themselves in print.',
        effects: { reputation: -1, communityTrust: 2 },
      },
    ],
  },
  {
    id: 'ev_practice_sliding_scale_ask',
    scope: 'practice',
    title: 'The Number She Can Manage',
    body: "The referral comes with a note in careful handwriting. T.O., 52 can do thirty a session and no more, and she would rather say so now than stop coming in six weeks. Your sliding-scale slots are full. The month's rent is not.",
    weight: 6,
    mood: 'sad',
    minDay: 14,
    choices: [
      {
        id: 'take_her_at_thirty',
        label: 'Take her at thirty',
        hint: '-$350 of fees this month. The rent gets tighter and she gets seen.',
        effects: {
          cash: -350,
          communityTrust: 8,
          reputation: 2,
          allMorale: 3,
          log: 'A sliding-scale slot opened where there was not one.',
        },
      },
      {
        id: 'real_date_in_six_weeks',
        label: 'Offer her a real date, six weeks out, in writing',
        hint: 'Honest, and six weeks is a long time when you are counting them.',
        effects: { communityTrust: 2 },
      },
      {
        id: 'refer_to_agency',
        label: 'Refer her on to the community agency you trust',
        hint: 'She gets seen within a fortnight. Just not by you.',
        effects: { communityTrust: 3, reputation: 1 },
      },
    ],
  },
  {
    id: 'ev_practice_letter_years_later',
    scope: 'practice',
    title: 'Four Years Later',
    body: "The envelope has the old address crossed out and the new one written underneath in biro. Inside: two paragraphs from somebody who sat in your worst chair through a bad winter, a photograph of a dog, and the sentence — I thought you would want to know I am still here.",
    weight: 3,
    once: true,
    mood: 'warm',
    minDay: 40,
    choices: [
      {
        id: 'pin_it_up',
        label: 'Pin it on the staff room wall',
        hint: 'Everybody reads it twice. Everybody works a little lighter for a week.',
        effects: {
          allMorale: 5,
          reputation: 1,
          log: 'A letter went up on the staff room wall. Nobody has taken it down.',
        },
      },
      {
        id: 'write_back',
        label: 'Write back',
        hint: 'Twenty minutes of your evening. Closes a circle that was left open.',
        effects: { allMorale: 3, communityTrust: 2 },
        outcome: 'You keep the draft short, because the long one was about you.',
      },
      {
        id: 'keep_it_private',
        label: 'Keep it in your desk drawer',
        hint: 'Yours. Some things are, and that is allowed.',
        effects: { allMorale: 2 },
      },
    ],
  },
  {
    id: 'ev_practice_records_mishap',
    scope: 'practice',
    title: 'The Wrong Attachment',
    body: "A discharge summary went to the right name at the wrong clinic. It sat open for nineteen minutes before the other practice rang, apologised for having read it, and deleted it. The client does not know yet.",
    weight: 4,
    mood: 'tense',
    minDay: 28,
    choices: [
      {
        id: 'disclose_today',
        label: 'Tell the client today, in person, with the whole timeline',
        hint: '-reputation in the short term. The only version of this you can defend.',
        effects: {
          reputation: -2,
          communityTrust: 6,
          allMorale: 2,
          setFlag: 'disclosed_breach',
          log: 'The breach was disclosed the same day, in person, with the times written down.',
        },
        outcome: 'She is angry for eleven minutes and then asks what you have changed.',
      },
      {
        id: 'disclose_and_fix',
        label: 'Disclose it, and buy records software that will not allow it again',
        hint: '-$750 and one hard conversation. It does not happen a second time.',
        requires: { minCash: 850 },
        effects: {
          cash: -750,
          reputation: -1,
          communityTrust: 7,
          allMorale: 3,
          setFlag: 'disclosed_breach',
        },
      },
      {
        id: 'log_internally',
        label: 'Log it internally and tighten the process quietly',
        hint: 'Nobody outside the building learns of it. Your staff know that you chose this.',
        effects: { allMorale: -4, setFlag: 'undisclosed_breach' },
      },
    ],
  },
  {
    id: 'ev_practice_waitlist_overflow',
    scope: 'practice',
    title: 'Nineteen Names',
    body: "The waitlist at {practice} is nineteen deep, and the oldest name has been on it since before the radiator was fixed. Two of them have rung twice this week. One of them has stopped ringing, which is the one you think about.",
    weight: 6,
    mood: 'tense',
    minDay: 25,
    choices: [
      {
        id: 'triage_day',
        label: 'Run a triage day — thirty minutes and a plan for every name',
        hint: '-$450 of billing. Nobody stays a name on a list.',
        effects: {
          cash: -450,
          communityTrust: 7,
          reputation: 3,
          allMorale: -2,
          log: 'Nineteen people got thirty minutes and a plan. Four of them needed nothing else.',
        },
      },
      {
        id: 'close_the_list',
        label: 'Close the list until you can honour it',
        hint: '-reputation and fewer referrals for a while. Capacity you can actually promise.',
        effects: {
          reputation: -2,
          communityTrust: 3,
          allMorale: 3,
          setFlag: 'list_closed',
        },
      },
      {
        id: 'push_through',
        label: 'Ask everyone to take one more client a week',
        hint: '+$600 now, and you will pay for it in energy and morale across the floor.',
        effects: { cash: 600, allMorale: -5, allEnergy: -12 },
      },
    ],
  },
  {
    id: 'ev_practice_cash_warning',
    scope: 'practice',
    title: 'The Number in Red',
    body: "The projection for {practice} does not reach the end of the month. Payroll is Friday. Nothing has failed yet — this is the part where you still get to choose which thing gives.",
    weight: 4,
    mood: 'tense',
    requires: { notFlag: 'credit_line_open' },
    choices: [
      {
        id: 'trim_costs',
        label: 'Trim everything that is not a room or a person',
        hint: '+$450 back this month. The good coffee is the first casualty.',
        effects: {
          cash: 450,
          allMorale: -3,
          setFlag: 'cash_warning_seen',
          log: 'Costs were trimmed at {practice}. The coffee is now an act of endurance.',
        },
      },
      {
        id: 'open_evenings',
        label: 'Open two evening slots a week and work them yourself',
        hint: '+$700 and a real dent in everyone\'s energy. Sustainable for about a month.',
        effects: {
          cash: 700,
          allEnergy: -10,
          allMorale: -2,
          setFlag: 'cash_warning_seen',
        },
      },
      {
        id: 'call_the_bank_early',
        label: 'Talk to the bank now, before it is urgent',
        hint: 'No money today. Better terms in three days than you would get in three weeks.',
        effects: {
          setFlag: 'cash_warning_seen',
          followUp: { eventId: 'ev_practice_line_of_credit', inDays: 3 },
          log: 'You booked a meeting with the bank while the numbers were still explainable.',
        },
      },
    ],
  },
  {
    id: 'ev_practice_line_of_credit',
    scope: 'practice',
    title: 'Terms, and What They Cost',
    body: "The bank will lend against next quarter's receivables. The manager is decent about it and says the phrase perfectly normal four times. It is perfectly normal. It is also money you will repay with hours earned in rooms like these.",
    weight: 3,
    mood: 'tense',
    requires: { notFlag: 'credit_line_open' },
    choices: [
      {
        id: 'take_full_line',
        label: 'Take the full line',
        hint: '+$1500 now. Repayments begin next quarter and they do not flex.',
        effects: {
          cash: 1500,
          allMorale: 2,
          setFlag: 'credit_line_open',
          log: '{practice} drew down the full credit line. Payroll cleared on Friday.',
        },
      },
      {
        id: 'take_half_line',
        label: 'Take half of what she offers',
        hint: '+$800 now, lighter repayments, less runway if it happens again.',
        effects: { cash: 800, setFlag: 'credit_line_open' },
      },
      {
        id: 'decline_and_cut',
        label: 'Decline the debt and cut deeper instead',
        hint: '+$300 from the cuts, no borrowing, and everybody feels the difference.',
        effects: {
          cash: 300,
          allMorale: -5,
          allEnergy: -8,
          setFlag: 'austerity',
        },
      },
    ],
  },
  {
    id: 'ev_practice_mentor_loan',
    scope: 'practice',
    title: 'Your Old Supervisor Picks Up on the Second Ring',
    body: "You ring the woman who supervised your first two hundred hours and get, as ever, three seconds of silence before she says anything useful. She has money that is not doing anything. She has conditions, and none of them are about interest.",
    weight: 3,
    mood: 'warm',
    requires: { notFlag: 'mentor_loan' },
    choices: [
      {
        id: 'accept_her_terms',
        label: 'Accept — and agree to her terms',
        hint: '+$1200. She wants a call on the first Monday of every month and two sliding-scale slots held open.',
        effects: {
          cash: 1200,
          communityTrust: 5,
          allMorale: 3,
          setFlag: 'mentor_loan',
          log: 'A loan arrived from your old supervisor, with two slots reserved and a standing phone call.',
        },
        outcome: 'The first Monday call runs ninety minutes. Eighty-five of them are supervision you did not know you needed.',
      },
      {
        id: 'take_less',
        label: 'Take less than she offers',
        hint: '+$600 and a lighter obligation. She will grumble about it for a year.',
        effects: { cash: 600, allMorale: 2, setFlag: 'mentor_loan' },
      },
      {
        id: 'advice_not_money',
        label: 'Decline the money. Take the advice',
        hint: 'No cash. An hour of the best consultation you will get all year.',
        effects: {
          reputation: 2,
          allMorale: 4,
          xp: 60,
          log: 'No money changed hands. You took four pages of notes.',
        },
      },
    ],
  },
  {
    id: 'ev_practice_soundproofing',
    scope: 'practice',
    title: 'Through the Wall',
    body: "The accountancy next door mentions — kindly, horrifyingly — that on Tuesdays they can hear the crying through the party wall. No names have carried. That is luck, and luck is not a confidentiality policy.",
    weight: 5,
    mood: 'tense',
    minDay: 18,
    choices: [
      {
        id: 'soundproof_properly',
        label: 'Have the wall done properly',
        hint: '-$850. Confidentiality stops depending on luck.',
        requires: { minCash: 950 },
        effects: {
          cash: -850,
          communityTrust: 6,
          reputation: 2,
          allMorale: 3,
          log: 'The party wall was lined and battened. The Tuesday room is a room again.',
        },
      },
      {
        id: 'white_noise',
        label: 'White noise machines, and move that room',
        hint: '-$180. Good enough for now, and honest with yourself about being good enough.',
        effects: { cash: -180, communityTrust: 2, allMorale: 2 },
      },
      {
        id: 'note_and_carry_on',
        label: 'Note it in the risk log and carry on',
        hint: 'Free. And you will think about it every Tuesday afternoon.',
        effects: { communityTrust: -4, allMorale: -3 },
      },
    ],
  },

  // ───────────────────────────────────────────────────────────────────────────
  // PROGRAM — one dilemma per running program
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: 'ev_program_group_empty_chair',
    scope: 'program',
    title: 'The Empty Chair',
    body: "Week six of the group, and the chair between R.K., 41 and the quiet man from the bakery has been empty twice running. The circle has started arranging itself around the gap without anybody mentioning it.",
    weight: 5,
    mood: 'curious',
    requires: { hasProgram: ['group_therapy'] },
    choices: [
      {
        id: 'name_the_absence',
        label: 'Name the absence in the room',
        hint: 'Uncomfortable for ten minutes. Usually the thing that holds a group together.',
        effects: {
          communityTrust: 2,
          allMorale: 2,
          reputation: 1,
          xp: 30,
          log: 'The group talked about the empty chair. Two people said more than they had in six weeks.',
        },
      },
      {
        id: 'call_between_sessions',
        label: 'Ring the missing member between sessions',
        hint: 'Costs the facilitator an evening. Sometimes they come back the following week.',
        effects: { therapistEnergy: -8, therapistMorale: 4, communityTrust: 3 },
      },
      {
        id: 'fill_the_seat',
        label: 'Fill the seat from the waitlist',
        hint: '+$350 in fees. A new member in week six changes the weather for everybody.',
        effects: { cash: 350, communityTrust: -2, allMorale: -2 },
      },
    ],
  },
  {
    id: 'ev_program_workshop_oversubscribed',
    scope: 'program',
    title: 'Sixty People for Thirty Chairs',
    body: "The Saturday workshop on sleep filled in a day and a half, and the waiting list for it is now longer than the workshop. The church hall across the road seats a hundred and smells permanently of coffee mornings.",
    weight: 5,
    mood: 'proud',
    requires: { hasProgram: ['workshops'] },
    choices: [
      {
        id: 'book_the_hall',
        label: 'Book the hall and run it big',
        hint: '+$900 after the hire, and a much wider door. Less intimate by a long way.',
        effects: {
          cash: 900,
          communityTrust: 6,
          reputation: 4,
          allEnergy: -8,
          log: 'Ninety-one people came to the church hall to be told that sleep is not a moral achievement.',
        },
      },
      {
        id: 'run_it_twice',
        label: 'Run it twice, same room, same Saturday',
        hint: '+$700, and a facilitator who loses their entire weekend.',
        effects: { cash: 700, reputation: 3, therapistMorale: -4, therapistEnergy: -14 },
      },
      {
        id: 'keep_it_small',
        label: 'Keep it to thirty and repeat it next month',
        hint: '+$300 only. The room stays a room where people actually talk.',
        effects: { cash: 300, communityTrust: 3, allMorale: 2 },
      },
    ],
  },
  {
    id: 'ev_program_school_year_nine',
    scope: 'program',
    title: 'The Year Nine Corridor',
    body: "The head of pastoral care asks for a quiet word and describes, carefully and without naming anybody, four students in one year group who have all stopped sleeping. She would like to know what you can actually do, and she would like the truthful answer.",
    weight: 5,
    mood: 'curious',
    requires: { hasProgram: ['school_partnership'] },
    choices: [
      {
        id: 'half_day_on_site',
        label: 'Commit a half-day a week on site',
        hint: '-$300 of clinic time, and a real presence in one corridor of one school.',
        effects: {
          cash: -300,
          communityTrust: 8,
          reputation: 3,
          allEnergy: -6,
          spawnReferral: { severityBias: -0.3 },
          log: 'A half-day a week now belongs to the school. The room they gave you has no window.',
        },
      },
      {
        id: 'train_their_staff',
        label: 'Train the pastoral team instead',
        hint: '+$250 for the training. You see nobody; twelve adults get better at noticing.',
        effects: { cash: 250, communityTrust: 5, reputation: 2 },
      },
      {
        id: 'name_your_limits',
        label: 'Say plainly what you cannot take on',
        hint: 'Disappointing and trustworthy. She will come to you first next time.',
        effects: { communityTrust: 3, reputation: 1 },
      },
    ],
  },
  {
    id: 'ev_program_crisis_line_long_night',
    scope: 'program',
    title: 'The Two A.M. Call',
    body: "{therapist} held the line from ten to two until the crew arrived at four minutes past three, talking about a dog, a sister in another city, and the weather. They filed the log at four and were back at reception at nine, which is the part that worries you.",
    weight: 5,
    mood: 'sad',
    requires: { hasProgram: ['crisis_line'] },
    choices: [
      {
        id: 'send_them_home',
        label: 'Send them home for the day, paid',
        hint: '-$250 to cover the gap. They come back a person rather than a witness.',
        effects: {
          cash: -250,
          therapistMorale: 11,
          therapistEnergy: 25,
          allMorale: 3,
          log: '{therapist} was sent home to sleep. The cover was worth every penny.',
        },
      },
      {
        id: 'team_debrief',
        label: 'Full team debrief before anybody takes another call',
        hint: 'Costs half a morning. Everyone learns what a good night on the line looks like.',
        effects: {
          allMorale: 4,
          allEnergy: -4,
          reputation: 2,
          xp: 40,
          setFlag: 'crisis_debrief_protocol',
        },
      },
      {
        id: 'they_say_theyre_fine',
        label: 'Let them work — they insist they are fine',
        hint: '+$200 kept. They are not fine, and it will be collected later with interest.',
        effects: { cash: 200, therapistMorale: -7, therapistEnergy: -15 },
      },
    ],
  },
  {
    id: 'ev_program_research_finding',
    scope: 'program',
    title: 'The Line in the Data',
    body: "Halfway through the study the numbers say something inconvenient: your drop-out rate is highest among exactly the people you most wanted to help. It is a real finding. It is also a finding with your name printed under it.",
    weight: 5,
    mood: 'curious',
    requires: { hasProgram: ['research_study'] },
    choices: [
      {
        id: 'publish_as_found',
        label: 'Write it up exactly as it is',
        hint: '+reputation with the people who read carefully. Some of it stings for a year.',
        effects: {
          reputation: 5,
          communityTrust: 5,
          allMorale: 2,
          xp: 60,
          log: 'The finding was published unsoftened. Two other clinics wrote to say thank you.',
        },
      },
      {
        id: 'publish_and_redesign',
        label: 'Publish it, and rebuild the intake process first',
        hint: '-$450 and six weeks of unglamorous work. The next cohort is different.',
        requires: { minCash: 550 },
        effects: {
          cash: -450,
          reputation: 4,
          communityTrust: 6,
          allMorale: 4,
          setFlag: 'intake_redesigned',
        },
      },
      {
        id: 'narrow_the_scope',
        label: 'Narrow the study\'s scope and move on',
        hint: 'A cleaner paper. The finding still exists; it just is not written down anywhere.',
        effects: { reputation: 2, allMorale: -3 },
      },
    ],
  },
  {
    id: 'ev_program_institute_extern',
    scope: 'program',
    title: 'The Extern Who Will Not Stop Apologising',
    body: "The new extern is bright, over-prepared, and has apologised eleven times before lunch. Her first solo intake was, by every account but hers, very good indeed. {therapist} wants to know how hard to push her.",
    weight: 5,
    mood: 'warm',
    requires: { hasProgram: ['training_institute'] },
    choices: [
      {
        id: 'protect_her_pace',
        label: 'Slow her caseload and build the confidence first',
        hint: 'A slower pipeline into the profession. She stays in it.',
        effects: {
          allMorale: 3,
          communityTrust: 2,
          xp: 30,
          setFlag: 'extern_supported',
        },
      },
      {
        id: 'stretch_her',
        label: 'Give her the harder case, with close supervision',
        hint: 'She grows fast or wobbles hard, and the supervision is the entire difference.',
        effects: {
          therapistMorale: 5,
          reputation: 2,
          allEnergy: -4,
          xp: 60,
          log: 'The extern took the harder case. {therapist} sat with her after every session for a fortnight.',
        },
      },
      {
        id: 'offer_the_job_now',
        label: 'Tell her now that there is a job here when she qualifies',
        hint: 'Commits you a year early. She stops apologising by Thursday.',
        effects: {
          therapistMorale: 6,
          allMorale: 4,
          reputation: 1,
          setFlag: 'extern_offer',
        },
        outcome: 'She says thank you four times and then, visibly, decides to believe it.',
      },
    ],
  },
];
