import type { Technique } from '../sim/types';

/**
 * Technique cards — the deck the player draws from mid-session.
 *
 * Invariants this file maintains (the content validator checks them):
 *  • 5 techniques per modality: two tier-1, two tier-2, one tier-3  → 40
 *  • 8 philosophy-exclusive tier-3 signature moves                  → 48 total
 *  • every technique has at least one `goodFor`
 *  • ids are `<modality>_<snake_name>`
 *
 * Design intent: a card should be obviously right in some rooms and obviously
 * wrong in others. Potent `progress` is always paid for — in energy, in
 * stability, in regression risk, or in how narrow the card's window is.
 * Anything genuinely activating (exposure, trauma processing, interpretation,
 * sculpting) carries a `minStability` gate, because you do not go toward the
 * hard thing with someone who is not steady enough to come back.
 */
export const TECHNIQUES: readonly Technique[] = [
  // ───────────────────────────────────────────────────────────────────────────
  // CBT
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: 'cbt_thought_record',
    name: 'Thought Record',
    modality: 'cbt',
    tier: 1,
    blurb: 'Catch a hot thought in writing — situation, feeling, evidence for, evidence against.',
    flavor: 'He wrote "everyone noticed" in the middle column, then could not name one of them.',
    focuses: ['build_skills', 'process'],
    goodFor: ['anxiety', 'depression', 'ocd'],
    poorFor: ['grief', 'psychosis'],
    effects: { progress: 1.0, quality: 0.03, resilience: 0.03 },
  },
  {
    id: 'cbt_activity_scheduling',
    name: 'Activity Scheduling',
    modality: 'cbt',
    tier: 1,
    blurb: 'Block the week out on paper — one small thing worth getting up for each day.',
    flavor: 'Tuesday, 10am: walk to the bakery on the corner. She circled it twice.',
    focuses: ['build_skills', 'stabilize'],
    goodFor: ['depression', 'burnout', 'bipolar'],
    effects: { progress: 0.9, quality: 0.02, stability: 0.05, resilience: 0.04 },
  },
  {
    id: 'cbt_behavioral_experiment',
    name: 'Behavioural Experiment',
    modality: 'cbt',
    tier: 2,
    blurb: 'Turn the fear into a written prediction, then go outside and find out what happens.',
    flavor: 'Prediction: they will laugh. Result: two people said hello, one asked the time.',
    focuses: ['build_skills', 'process'],
    goodFor: ['anxiety', 'ocd', 'eating'],
    poorFor: ['psychosis', 'grief'],
    minStability: 0.5,
    effects: { progress: 1.2, quality: 0.04, stability: -0.03, resilience: 0.06, energy: 2, breakthrough: 0.02 },
  },
  {
    id: 'cbt_cognitive_restructuring',
    name: 'Cognitive Restructuring',
    modality: 'cbt',
    tier: 2,
    blurb: 'Take the belief apart at the joints and see which pieces actually hold weight.',
    flavor: '"I am a burden" survived four questions. It did not survive the fifth.',
    focuses: ['process', 'build_skills'],
    goodFor: ['depression', 'anxiety', 'identity', 'burnout'],
    poorFor: ['psychosis'],
    effects: { progress: 1.15, quality: 0.04, resilience: 0.04, energy: 1 },
  },
  {
    id: 'cbt_exposure_hierarchy',
    name: 'Exposure Hierarchy',
    modality: 'cbt',
    tier: 3,
    blurb: 'Climb the ladder a rung at a time and stay in it until the fear curve bends.',
    flavor: 'Eleven minutes in the lift with the doors shut. Somewhere in there he stopped counting.',
    focuses: ['process'],
    goodFor: ['anxiety', 'ocd', 'trauma'],
    poorFor: ['psychosis', 'bipolar'],
    chapters: ['work', 'consolidation'],
    minStability: 0.6,
    effects: {
      progress: 1.4,
      quality: 0.06,
      stability: -0.07,
      resilience: 0.08,
      energy: 4,
      regression: 1.35,
      breakthrough: 0.05,
    },
  },

  // ───────────────────────────────────────────────────────────────────────────
  // DBT
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: 'dbt_distress_tolerance',
    name: 'TIPP & Distress Tolerance',
    modality: 'dbt',
    tier: 1,
    blurb: 'Cold water, paced breathing, a hard sixty seconds — settle the body before the talking.',
    flavor: 'Cold water at the wrists, count of six out. By the third round her hands were hers again.',
    focuses: ['stabilize'],
    goodFor: ['bipolar', 'substance', 'trauma', 'eating'],
    effects: { progress: 0.8, quality: 0.02, rapport: 0.02, stability: 0.1, regression: 0.6 },
  },
  {
    id: 'dbt_wise_mind',
    name: 'Wise Mind',
    modality: 'dbt',
    tier: 1,
    blurb: 'Find the place between the hot answer and the cold one, and ask it what it knows.',
    flavor: 'Emotion mind said burn it down. Reason mind said do nothing. Wise mind said: send one text.',
    goodFor: ['bipolar', 'identity', 'relationship', 'substance'],
    poorFor: ['psychosis'],
    effects: { progress: 0.95, quality: 0.03, stability: 0.06, resilience: 0.03 },
  },
  {
    id: 'dbt_opposite_action',
    name: 'Opposite Action',
    modality: 'dbt',
    tier: 2,
    blurb: 'Name the urge, check it against the facts, then do the exact opposite on purpose.',
    flavor: 'The urge said stay under the duvet. She put shoes on and stood in the doorway a while.',
    focuses: ['build_skills', 'process'],
    goodFor: ['depression', 'anxiety', 'relationship', 'burnout'],
    poorFor: ['psychosis'],
    minStability: 0.5,
    effects: { progress: 1.2, quality: 0.04, stability: -0.02, resilience: 0.07, energy: 2 },
  },
  {
    id: 'dbt_dear_man',
    name: 'DEAR MAN',
    modality: 'dbt',
    tier: 2,
    blurb: 'Rehearse the ask out loud — describe, express, assert, and hold the line kindly.',
    flavor: 'They practised the sentence eleven times. The twelfth one was for her mother.',
    focuses: ['build_skills'],
    goodFor: ['relationship', 'identity', 'burnout'],
    poorFor: ['grief'],
    effects: { progress: 1.1, quality: 0.04, rapport: 0.02, resilience: 0.07, energy: 1 },
  },
  {
    id: 'dbt_chain_analysis',
    name: 'Behavioural Chain Analysis',
    modality: 'dbt',
    tier: 3,
    blurb: 'Walk the chain backwards, link by link, from the prompting event to the thing that gave way.',
    flavor: 'Twenty-two links from a missed phone call to Thursday night. Link nine had a door in it.',
    focuses: ['process'],
    goodFor: ['substance', 'eating', 'behavioral', 'bipolar'],
    poorFor: ['grief', 'psychosis'],
    chapters: ['work'],
    minStability: 0.55,
    effects: {
      progress: 1.35,
      quality: 0.06,
      stability: -0.05,
      resilience: 0.09,
      energy: 4,
      regression: 1.2,
      breakthrough: 0.04,
    },
  },

  // ───────────────────────────────────────────────────────────────────────────
  // EMDR
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: 'emdr_resource_installation',
    name: 'Resource Installation',
    modality: 'emdr',
    tier: 1,
    blurb: 'Build a calm place and a protector figure first, and tap them in until they hold.',
    flavor: "The safe place was her grandmother's kitchen. The door locked from the inside.",
    focuses: ['stabilize'],
    goodFor: ['trauma', 'anxiety', 'grief', 'identity'],
    effects: { progress: 0.85, quality: 0.03, rapport: 0.03, stability: 0.09, resilience: 0.05, energy: 1, regression: 0.6 },
  },
  {
    id: 'emdr_container_exercise',
    name: 'Container Exercise',
    modality: 'emdr',
    tier: 1,
    blurb: "Choose a box strong enough to hold what won't fit in today, and shut the lid together.",
    flavor: 'He picked a steel toolbox with two clasps. It stayed shut all week, which surprised him.',
    focuses: ['stabilize'],
    goodFor: ['trauma', 'anxiety', 'ocd'],
    effects: { progress: 0.8, quality: 0.02, stability: 0.1, regression: 0.55 },
  },
  {
    id: 'emdr_float_back',
    name: 'Float-Back',
    modality: 'emdr',
    tier: 2,
    blurb: 'Follow the feeling backwards to the earliest time it showed up wearing the same face.',
    flavor: "The lift lurched and suddenly he was nine, on a stairwell, holding somebody else's coat.",
    focuses: ['process'],
    goodFor: ['trauma', 'anxiety', 'identity'],
    poorFor: ['psychosis', 'bipolar'],
    chapters: ['work'],
    minStability: 0.55,
    effects: { progress: 1.25, quality: 0.05, stability: -0.05, energy: 3, regression: 1.25, breakthrough: 0.03 },
  },
  {
    id: 'emdr_cognitive_interweave',
    name: 'Cognitive Interweave',
    modality: 'emdr',
    tier: 2,
    blurb: 'When the processing loops, offer one question that lets an adult perspective in.',
    flavor: '"Whose job was it to keep that child safe?" The answer took a minute, and it was not hers.',
    focuses: ['process'],
    goodFor: ['trauma', 'grief', 'identity'],
    minStability: 0.5,
    effects: { progress: 1.2, quality: 0.05, rapport: 0.03, stability: 0.03, energy: 2, regression: 0.8 },
  },
  {
    id: 'emdr_bilateral_processing',
    name: 'Bilateral Processing',
    modality: 'emdr',
    tier: 3,
    blurb: 'Hold the worst image, follow the lights, and run the sets until the charge comes down.',
    flavor: 'Set after set the photograph lost its colour. By the end it was a room he used to know.',
    focuses: ['process'],
    goodFor: ['trauma', 'grief', 'anxiety'],
    poorFor: ['psychosis', 'bipolar', 'substance'],
    chapters: ['work'],
    minStability: 0.65,
    effects: {
      progress: 1.45,
      quality: 0.07,
      stability: -0.08,
      resilience: 0.05,
      energy: 5,
      regression: 1.5,
      breakthrough: 0.07,
    },
  },

  // ───────────────────────────────────────────────────────────────────────────
  // Somatic
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: 'somatic_grounding',
    name: 'Grounding',
    modality: 'somatic',
    tier: 1,
    blurb: 'Feet on the floor, weight into the chair, five things in the room that are true right now.',
    flavor: 'Four things she could see, three she could hear. The radiator ticked. She stayed.',
    focuses: ['stabilize'],
    goodFor: ['anxiety', 'trauma', 'psychosis', 'substance'],
    effects: { progress: 0.8, quality: 0.02, rapport: 0.02, stability: 0.1, regression: 0.55 },
  },
  {
    id: 'somatic_orienting',
    name: 'Orienting',
    modality: 'somatic',
    tier: 1,
    blurb: "Let the eyes travel the room slowly until the nervous system agrees there's no lion.",
    flavor: 'He turned his head toward the window without being asked. His shoulders came down an inch.',
    focuses: ['stabilize', 'build_skills'],
    goodFor: ['trauma', 'anxiety', 'psychosis'],
    chapters: ['trust'],
    effects: { progress: 0.85, quality: 0.03, rapport: 0.04, stability: 0.08 },
  },
  {
    id: 'somatic_body_scan',
    name: 'Body Scan',
    modality: 'somatic',
    tier: 2,
    blurb: 'Move attention from scalp to soles, reporting what is there without fixing any of it.',
    flavor: 'Jaw: clenched. Shoulders: up by the ears. She said "oh," like meeting a stranger.',
    focuses: ['build_skills', 'stabilize'],
    goodFor: ['burnout', 'anxiety', 'eating', 'depression'],
    poorFor: ['trauma', 'psychosis'],
    effects: { progress: 1.0, quality: 0.04, stability: 0.05, resilience: 0.05, energy: 1 },
  },
  {
    id: 'somatic_titration',
    name: 'Titration',
    modality: 'somatic',
    tier: 2,
    blurb: 'Take the memory a teaspoon at a time, pausing to let the body catch up between sips.',
    flavor: 'One drop of it, then back to the window. One drop, then the window. Nobody drowned.',
    focuses: ['process', 'stabilize'],
    goodFor: ['trauma', 'grief', 'anxiety'],
    effects: { progress: 1.1, quality: 0.05, stability: 0.04, resilience: 0.06, energy: 2, regression: 0.7 },
  },
  {
    id: 'somatic_pendulation',
    name: 'Pendulation',
    modality: 'somatic',
    tier: 3,
    blurb: 'Swing between the tight place and the easy place until the body remembers it can move.',
    flavor: 'Chest, then hands. Chest, then hands. On the fifth pass the chest let go first.',
    focuses: ['process'],
    goodFor: ['trauma', 'grief', 'anxiety'],
    poorFor: ['psychosis'],
    chapters: ['work', 'consolidation'],
    minStability: 0.6,
    effects: {
      progress: 1.3,
      quality: 0.06,
      stability: 0.02,
      resilience: 0.08,
      energy: 4,
      regression: 0.75,
      breakthrough: 0.04,
    },
  },

  // ───────────────────────────────────────────────────────────────────────────
  // Psychodynamic
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: 'psychodynamic_free_association',
    name: 'Free Association',
    modality: 'psychodynamic',
    tier: 1,
    blurb: "Ask for whatever's there, unedited, and follow the drift without steering it.",
    flavor: 'Nine minutes about a bicycle, and then, quite quietly, about her father.',
    focuses: ['process'],
    goodFor: ['identity', 'depression', 'grief', 'relationship'],
    poorFor: ['ocd', 'psychosis'],
    effects: { progress: 0.95, quality: 0.03, rapport: 0.05, energy: 1 },
  },
  {
    id: 'psychodynamic_attachment_mapping',
    name: 'Attachment Mapping',
    modality: 'psychodynamic',
    tier: 1,
    blurb: 'Sketch who they turned to as a child and who they turn to now, then set the lists side by side.',
    flavor: 'The childhood column had one name in it. The present column had the same name, crossed out.',
    focuses: ['process', 'build_skills'],
    goodFor: ['relationship', 'identity', 'trauma', 'grief'],
    chapters: ['trust', 'work'],
    effects: { progress: 1.0, quality: 0.03, rapport: 0.06, resilience: 0.03, energy: 1 },
  },
  {
    id: 'psychodynamic_dream_material',
    name: 'Dream Material',
    modality: 'psychodynamic',
    tier: 2,
    blurb: "Take the dream seriously — a letter from somewhere the words haven't reached yet.",
    flavor: 'In the dream the house had one more room. He kept saying he had never been inside it.',
    focuses: ['process'],
    goodFor: ['grief', 'identity', 'trauma', 'anxiety'],
    poorFor: ['adhd', 'behavioral'],
    chapters: ['work'],
    effects: { progress: 1.1, quality: 0.04, rapport: 0.04, energy: 2, breakthrough: 0.03 },
  },
  {
    id: 'psychodynamic_defense_interpretation',
    name: 'Defence Interpretation',
    modality: 'psychodynamic',
    tier: 2,
    blurb: 'Name the move they make whenever the subject gets close — gently, and by its right name.',
    flavor: '"You made a joke there." A long pause. "I do that," she said, and made no more of them.',
    focuses: ['process'],
    goodFor: ['identity', 'relationship', 'substance', 'eating'],
    poorFor: ['trauma', 'psychosis'],
    minStability: 0.55,
    effects: {
      progress: 1.25,
      quality: 0.05,
      rapport: -0.04,
      stability: -0.04,
      energy: 3,
      regression: 1.2,
      breakthrough: 0.03,
    },
  },
  {
    id: 'psychodynamic_transference_work',
    name: 'Transference Work',
    modality: 'psychodynamic',
    tier: 3,
    blurb: 'Use what is happening in this room, between the two of you, as the live material.',
    flavor: '"You went quiet when I looked at the clock." He nodded. "Everyone is always leaving."',
    focuses: ['process'],
    goodFor: ['relationship', 'identity', 'trauma', 'depression'],
    poorFor: ['psychosis', 'behavioral'],
    chapters: ['work', 'consolidation'],
    minStability: 0.6,
    effects: {
      progress: 1.35,
      quality: 0.07,
      rapport: 0.06,
      stability: -0.05,
      energy: 4,
      regression: 1.25,
      breakthrough: 0.06,
    },
  },

  // ───────────────────────────────────────────────────────────────────────────
  // ACT
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: 'act_values_clarification',
    name: 'Values Clarification',
    modality: 'act',
    tier: 1,
    blurb: 'Set the symptoms aside and ask what they would want their life to be about anyway.',
    flavor: 'He wrote "be someone my brother can call." Then he looked at his phone for a while.',
    focuses: ['build_skills', 'stabilize'],
    goodFor: ['burnout', 'depression', 'identity', 'substance'],
    effects: { progress: 0.95, quality: 0.03, rapport: 0.03, resilience: 0.05 },
  },
  {
    id: 'act_cognitive_defusion',
    name: 'Cognitive Defusion',
    modality: 'act',
    tier: 1,
    blurb: 'Put "I am having the thought that…" in front of it and watch it lose some teeth.',
    flavor: 'She sang the sentence to the tune of a nursery rhyme and laughed at herself, briefly.',
    focuses: ['build_skills'],
    goodFor: ['anxiety', 'ocd', 'depression', 'identity'],
    poorFor: ['grief'],
    effects: { progress: 1.0, quality: 0.03, stability: 0.03, resilience: 0.06 },
  },
  {
    id: 'act_acceptance_willingness',
    name: 'Acceptance & Willingness',
    modality: 'act',
    tier: 2,
    blurb: 'Stop wrestling the feeling to the ground and practise carrying it instead.',
    flavor: '"What if it just rides along?" She opened her hands on her knees and tried it.',
    focuses: ['process', 'stabilize'],
    goodFor: ['grief', 'anxiety', 'burnout', 'eating'],
    minStability: 0.5,
    effects: { progress: 1.15, quality: 0.05, stability: 0.04, resilience: 0.07, energy: 2, regression: 0.8 },
  },
  {
    id: 'act_committed_action',
    name: 'Committed Action',
    modality: 'act',
    tier: 2,
    blurb: 'Turn the value into one thing small enough to actually do before Thursday.',
    flavor: '"Call the brother" became "text the brother" became a sent message at 9:40pm.',
    focuses: ['build_skills'],
    goodFor: ['depression', 'substance', 'burnout', 'adhd'],
    poorFor: ['bipolar', 'psychosis'],
    effects: { progress: 1.2, quality: 0.04, resilience: 0.08, energy: 2 },
  },
  {
    id: 'act_self_as_context',
    name: 'Self-as-Context',
    modality: 'act',
    tier: 3,
    blurb: 'Separate the person from the story they are inside — the sky is not the weather.',
    flavor: '"The one who noticed all of it is still here." He sat with that for the rest of the hour.',
    focuses: ['process', 'build_skills'],
    goodFor: ['identity', 'trauma', 'depression', 'eating'],
    poorFor: ['psychosis', 'behavioral'],
    chapters: ['work', 'consolidation'],
    minStability: 0.55,
    effects: { progress: 1.3, quality: 0.07, stability: 0.03, resilience: 0.1, energy: 4, breakthrough: 0.05 },
  },

  // ───────────────────────────────────────────────────────────────────────────
  // Play
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: 'play_sand_tray',
    name: 'Sand Tray',
    modality: 'play',
    tier: 1,
    blurb: "Open the shelf of figures and let them build the thing they can't say yet.",
    flavor: 'He buried the small horse, dug it up, then buried it again — more carefully the second time.',
    focuses: ['stabilize', 'process'],
    goodFor: ['behavioral', 'trauma', 'grief', 'adhd'],
    effects: { progress: 0.9, quality: 0.03, rapport: 0.07, stability: 0.05, energy: 1 },
  },
  {
    id: 'play_therapeutic_games',
    name: 'Therapeutic Games',
    modality: 'play',
    tier: 1,
    blurb: 'Play something with rules and turns, and lose gracefully on purpose.',
    flavor: 'She won at cards twice, then told him about the new school without looking up.',
    focuses: ['stabilize', 'build_skills'],
    goodFor: ['behavioral', 'adhd', 'anxiety'],
    chapters: ['trust'],
    effects: { progress: 0.85, quality: 0.02, rapport: 0.09, stability: 0.04 },
  },
  {
    id: 'play_art_externalising',
    name: 'Externalising Through Art',
    modality: 'play',
    tier: 2,
    blurb: 'Give the worry a face and a name so it becomes something in the room, not in them.',
    flavor: 'The Worry was drawn green, with too many legs. He named it Kevin and made it smaller.',
    focuses: ['process', 'build_skills'],
    goodFor: ['behavioral', 'trauma', 'anxiety', 'grief'],
    effects: { progress: 1.1, quality: 0.04, rapport: 0.05, resilience: 0.05, energy: 1 },
  },
  {
    id: 'play_puppet_narrative',
    name: 'Puppet Narrative',
    modality: 'play',
    tier: 2,
    blurb: 'Hand over the puppets and let the story get told by somebody who is not them.',
    flavor: 'The fox explained, at length, why nobody had come to the door that night.',
    focuses: ['process'],
    goodFor: ['behavioral', 'trauma', 'relationship', 'adhd'],
    chapters: ['work'],
    minStability: 0.5,
    effects: { progress: 1.2, quality: 0.05, rapport: 0.04, stability: -0.02, energy: 2, breakthrough: 0.03 },
  },
  {
    id: 'play_parent_coaching',
    name: 'Parent Coaching',
    modality: 'play',
    tier: 3,
    blurb: 'Coach the grown-ups: labelled praise, one clear instruction, and the same bedtime every night.',
    flavor: 'Dad practised "thank you for putting your shoes on" without adding anything after it.',
    focuses: ['build_skills'],
    goodFor: ['behavioral', 'adhd', 'relationship', 'anxiety'],
    chapters: ['work', 'consolidation'],
    effects: {
      progress: 1.3,
      quality: 0.06,
      stability: 0.05,
      resilience: 0.1,
      energy: 4,
      regression: 0.7,
      breakthrough: 0.03,
    },
  },

  // ───────────────────────────────────────────────────────────────────────────
  // Family systems
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: 'family_genogram',
    name: 'Genogram',
    modality: 'family',
    tier: 1,
    blurb: 'Draw three generations on one sheet and see which patterns keep showing up.',
    flavor: 'Three generations of leaving at thirty-one. She noticed her own birthday coming.',
    focuses: ['stabilize', 'build_skills'],
    goodFor: ['relationship', 'identity', 'substance', 'grief'],
    chapters: ['trust'],
    effects: { progress: 0.9, quality: 0.03, rapport: 0.05, energy: 1 },
  },
  {
    id: 'family_circular_questioning',
    name: 'Circular Questioning',
    modality: 'family',
    tier: 1,
    blurb: 'Ask each person what they think someone else in the room is feeling.',
    flavor: '"What does your brother think your mum worries about?" The brother looked up, startled.',
    goodFor: ['relationship', 'behavioral', 'adhd', 'identity'],
    effects: { progress: 1.0, quality: 0.03, rapport: 0.04, energy: 1 },
  },
  {
    id: 'family_structural_boundary',
    name: 'Structural Boundary Work',
    modality: 'family',
    tier: 2,
    blurb: 'Redraw who decides what — parents in one seat, children out of the middle.',
    flavor: 'The twelve-year-old was told, kindly, that the rota was not her job. She cried, then slept.',
    focuses: ['build_skills', 'process'],
    goodFor: ['relationship', 'behavioral', 'adhd', 'eating'],
    poorFor: ['grief'],
    minStability: 0.5,
    effects: { progress: 1.2, quality: 0.05, rapport: -0.03, stability: 0.03, resilience: 0.07, energy: 3 },
  },
  {
    id: 'family_reflecting_team',
    name: 'Reflecting Team',
    modality: 'family',
    tier: 2,
    blurb: 'Let the family listen while the clinicians talk about them, warmly and out loud.',
    flavor: 'They heard themselves called "exhausted and still trying." Nobody had said trying before.',
    focuses: ['process'],
    goodFor: ['relationship', 'identity', 'psychosis', 'eating'],
    effects: { progress: 1.15, quality: 0.05, rapport: 0.05, energy: 2, breakthrough: 0.03 },
  },
  {
    id: 'family_sculpting',
    name: 'Family Sculpting',
    modality: 'family',
    tier: 3,
    blurb: 'Ask them to stand the family in the room the way it actually feels, then move one person.',
    flavor: 'She placed her father facing the wall. He turned round on his own, and the room went quiet.',
    focuses: ['process'],
    goodFor: ['relationship', 'identity', 'behavioral', 'trauma'],
    poorFor: ['psychosis'],
    chapters: ['work'],
    minStability: 0.55,
    effects: {
      progress: 1.35,
      quality: 0.07,
      rapport: 0.04,
      stability: -0.05,
      energy: 4,
      regression: 1.2,
      breakthrough: 0.06,
    },
  },

  // ───────────────────────────────────────────────────────────────────────────
  // Philosophy — Trauma-Informed Center
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: 'emdr_flash_technique',
    name: 'The Flash Technique',
    modality: 'emdr',
    tier: 3,
    blurb: 'Keep their attention on something good and blink through the memory in flashes, never looking straight at it.',
    flavor: 'They talked about the dog the whole time. Somewhere in there the corridor stopped mattering.',
    focuses: ['process', 'stabilize'],
    goodFor: ['trauma', 'grief', 'anxiety'],
    poorFor: ['psychosis'],
    minStability: 0.5,
    philosophy: 'trauma_informed',
    effects: {
      progress: 1.3,
      quality: 0.06,
      stability: 0.02,
      resilience: 0.06,
      energy: 4,
      regression: 0.65,
      breakthrough: 0.05,
    },
  },
  {
    id: 'somatic_sequencing',
    name: 'Sequencing the Interrupted Defence',
    modality: 'somatic',
    tier: 3,
    blurb: 'Find the movement the body never got to finish, and let it finish now, very slowly.',
    flavor: 'His arm came up eight inches, then further. Twenty years late, he pushed something away.',
    focuses: ['process'],
    goodFor: ['trauma', 'anxiety', 'grief'],
    poorFor: ['psychosis', 'bipolar'],
    chapters: ['work'],
    minStability: 0.6,
    philosophy: 'trauma_informed',
    effects: {
      progress: 1.4,
      quality: 0.07,
      stability: -0.04,
      resilience: 0.1,
      energy: 5,
      regression: 1.15,
      breakthrough: 0.06,
    },
  },
  {
    id: 'psychodynamic_parts_work',
    name: 'Parts Work',
    modality: 'psychodynamic',
    tier: 3,
    blurb: 'Ask the part that is shouting what it thinks would happen if it ever stopped.',
    flavor: '"It has been on watch since she was eleven. Nobody ever offered to take a shift."',
    focuses: ['process', 'stabilize'],
    goodFor: ['trauma', 'identity', 'eating', 'substance'],
    poorFor: ['psychosis'],
    minStability: 0.55,
    philosophy: 'trauma_informed',
    effects: {
      progress: 1.3,
      quality: 0.07,
      rapport: 0.06,
      stability: 0.03,
      resilience: 0.08,
      energy: 4,
      regression: 0.8,
      breakthrough: 0.05,
    },
  },

  // ───────────────────────────────────────────────────────────────────────────
  // Philosophy — Family & Community Clinic
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: 'family_multi_family_group',
    name: 'Multi-Family Group',
    modality: 'family',
    tier: 3,
    blurb: 'Put six families in one room and let the ones a year further along do the reassuring.',
    flavor: 'Another mother said "year two is easier." It landed the way nothing from a clinician had.',
    focuses: ['build_skills', 'stabilize'],
    goodFor: ['psychosis', 'behavioral', 'eating', 'substance'],
    poorFor: ['trauma'],
    chapters: ['work', 'consolidation'],
    philosophy: 'family_community',
    effects: {
      progress: 1.25,
      quality: 0.06,
      rapport: 0.05,
      stability: 0.06,
      resilience: 0.09,
      energy: 4,
      regression: 0.7,
    },
  },
  {
    id: 'family_network_meeting',
    name: 'Open Dialogue Network Meeting',
    modality: 'family',
    tier: 3,
    blurb: 'Gather everyone who matters — family, the GP, the neighbour — and make no decision without them in the room.',
    flavor: 'Seven people, one circle, no meetings about her without her. Her brother spoke first.',
    focuses: ['stabilize', 'process'],
    goodFor: ['psychosis', 'bipolar', 'relationship', 'identity'],
    philosophy: 'family_community',
    effects: {
      progress: 1.25,
      quality: 0.07,
      rapport: 0.07,
      stability: 0.08,
      resilience: 0.05,
      energy: 5,
      regression: 0.6,
      breakthrough: 0.04,
    },
  },
  {
    id: 'play_parent_child_interaction',
    name: 'Parent–Child Interaction Coaching',
    modality: 'play',
    tier: 3,
    blurb: 'Coach through an earpiece while they play — praise the good, ignore the small stuff, mean the limits.',
    flavor: 'Ten minutes of special time: no questions, no commands. By day four he was asking for it.',
    focuses: ['build_skills'],
    goodFor: ['behavioral', 'adhd', 'anxiety', 'trauma'],
    poorFor: ['identity'],
    chapters: ['work', 'consolidation'],
    philosophy: 'family_community',
    effects: {
      progress: 1.3,
      quality: 0.06,
      rapport: 0.06,
      stability: 0.05,
      resilience: 0.1,
      energy: 4,
      regression: 0.65,
      breakthrough: 0.04,
    },
  },

  // ───────────────────────────────────────────────────────────────────────────
  // Philosophy — Integrative Wellness Studio
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: 'act_mindful_self_compassion',
    name: 'Mindful Self-Compassion',
    modality: 'act',
    tier: 3,
    blurb: 'A hand on the chest, and the question: what would you say to a friend standing in this exact spot?',
    flavor: '"I would tell them it was not their fault." A long silence. "Yeah. I heard it."',
    focuses: ['stabilize', 'build_skills'],
    goodFor: ['burnout', 'eating', 'depression', 'identity', 'grief'],
    philosophy: 'integrative_wellness',
    effects: {
      progress: 1.2,
      quality: 0.06,
      rapport: 0.05,
      stability: 0.07,
      resilience: 0.1,
      energy: 3,
      regression: 0.65,
    },
  },
  {
    id: 'somatic_interoceptive_training',
    name: 'Interoceptive Awareness Training',
    modality: 'somatic',
    tier: 3,
    blurb: 'Relearn hunger, thirst and heartbeat as signals rather than alarms, one measured minute at a time.',
    flavor: 'She counted her own pulse and got it nearly right. "That is mine," she said. "That is just mine."',
    focuses: ['build_skills', 'stabilize'],
    goodFor: ['eating', 'anxiety', 'burnout', 'substance'],
    poorFor: ['trauma'],
    minStability: 0.5,
    philosophy: 'integrative_wellness',
    effects: {
      progress: 1.25,
      quality: 0.06,
      stability: 0.05,
      resilience: 0.09,
      energy: 3,
      regression: 0.7,
      breakthrough: 0.03,
    },
  },
] as const;
