import type { UpgradeDef } from '../sim/types';

/**
 * Practice upgrades — the slow, tangible improvement of a place.
 *
 * Four categories:
 *  - office        the room itself: comfort, privacy, light, capacity
 *  - tech          the quiet infrastructure that buys back evenings
 *  - certification what the team is permitted and equipped to do
 *  - automation    labour saved, arriving just before the tedium does
 *
 * Every mod here is deliberately small. An upgrade should feel like the office
 * exhaling, not like a stat spike. The tree is gated with `requires` so the
 * clinic grows in a believable order: you get a door that closes properly
 * before you get a sound-masking system to sit behind it.
 */
export const UPGRADES: readonly UpgradeDef[] = [
  // ── Office ────────────────────────────────────────────────────────────────
  {
    id: 'up_waiting_room',
    name: 'A Proper Waiting Room',
    blurb: 'Two lamps, a coat hook, magazines from this decade. Nobody waits in the corridor now.',
    cost: 250,
    category: 'office',
    mods: { quality: 0.02, moraleDrift: 0.2 },
    icon: '🛋️',
  },
  {
    id: 'up_kettle_and_mugs',
    name: 'Kettle & Good Mugs',
    blurb: 'Mugs heavy enough to hold with both hands. A small ceremony before a hard hour.',
    cost: 320,
    category: 'office',
    mods: { moraleDrift: 0.35 },
    icon: '🫖',
  },
  {
    id: 'up_bike_rack',
    name: 'Covered Bike Rack',
    blurb: 'A shelter by the side door. Three of your staff stop arriving damp and apologising.',
    cost: 450,
    category: 'office',
    mods: { energyRegenMult: 1.03, moraleDrift: 0.25 },
    icon: '🚲',
  },
  {
    id: 'up_good_chairs',
    name: 'Chairs Worth Sitting In',
    blurb: 'Deep seats, low arms, fabric that forgives tears. Nobody perches anymore.',
    cost: 600,
    category: 'office',
    requires: { hasUpgrade: ['up_waiting_room'] },
    mods: { quality: 0.03, moraleDrift: 0.2 },
    icon: '🪑',
  },
  {
    id: 'up_lending_library',
    name: 'The Lending Shelf',
    blurb: 'One shelf, forty paperbacks, an honour-system clipboard. Half come back annotated.',
    cost: 700,
    category: 'office',
    requires: { minPracticeLevel: 2 },
    mods: { quality: 0.01, referralMult: 1.04 },
    icon: '📚',
  },
  {
    id: 'up_plant_wall',
    name: 'The Plant Wall',
    blurb: 'Pothos, fern, one stubborn monstera. Clients touch the leaves on their way out.',
    cost: 780,
    category: 'office',
    requires: { minPracticeLevel: 2 },
    mods: { quality: 0.02, moraleDrift: 0.4 },
    icon: '🪴',
  },
  {
    id: 'up_soundproof_door',
    name: 'Soundproofed Door',
    blurb: 'Solid core, proper sweep along the floor. What is said in the room stays in the room.',
    cost: 900,
    category: 'office',
    requires: { minPracticeLevel: 2 },
    mods: { quality: 0.03 },
    icon: '🚪',
  },
  {
    id: 'up_second_bathroom',
    name: 'A Second Bathroom',
    blurb: 'Deeply unglamorous. Top of every staff survey ever run, in every clinic, everywhere.',
    cost: 1900,
    category: 'office',
    requires: { minPracticeLevel: 3 },
    mods: { quality: 0.01, capacity: 1, moraleDrift: 0.3 },
    icon: '🚻',
  },
  {
    id: 'up_nap_room',
    name: 'The Nap Room',
    blurb: 'A daybed, a folded blanket, a twenty-minute timer. Nobody asks what you were doing in there.',
    cost: 2400,
    category: 'office',
    requires: { minPracticeLevel: 3 },
    mods: { energyRegenMult: 1.12, moraleDrift: 0.4 },
    icon: '😴',
  },
  {
    id: 'up_skylight',
    name: 'Skylight Over the Stairs',
    blurb: 'Cut into the roof in one loud weekend. Four o’clock stops feeling like a basement.',
    cost: 2600,
    category: 'office',
    requires: { minPracticeLevel: 4, minCash: 4000 },
    mods: { quality: 0.03, energyRegenMult: 1.05, moraleDrift: 0.5 },
    icon: '🌤️',
  },
  {
    id: 'up_supervision_room',
    name: 'Supervision Room',
    blurb: 'A round table and a whiteboard for the cases that keep people up. Hard work gets witnessed.',
    cost: 3200,
    category: 'office',
    requires: { minPracticeLevel: 4, minTherapists: 3 },
    mods: { quality: 0.03, moraleDrift: 0.6, capacity: 1 },
    icon: '🫂',
  },
  {
    id: 'up_group_room',
    name: 'The Group Room',
    blurb: 'Eight chairs in a circle, tissues in the middle, no desk anywhere in sight.',
    cost: 3800,
    category: 'office',
    requires: { minPracticeLevel: 4 },
    mods: { capacity: 3, quality: 0.01, unlockSessionType: 'group' },
    icon: '🧑‍🤝‍🧑',
  },

  // ── Tech ──────────────────────────────────────────────────────────────────
  {
    id: 'up_sound_masking',
    name: 'Sound-Masking System',
    blurb: 'A low band of pink noise in the corridor. The waiting room stops overhearing the hard parts.',
    cost: 1400,
    category: 'tech',
    requires: { hasUpgrade: ['up_soundproof_door'] },
    mods: { quality: 0.04 },
    icon: '🎚️',
  },
  {
    id: 'up_telehealth_kit',
    name: 'Telehealth Kit',
    blurb: 'Honest camera, kind microphone, a lamp at eye level. Snowed-in weeks stop cancelling themselves.',
    cost: 1600,
    category: 'tech',
    requires: { minPracticeLevel: 2 },
    mods: { capacity: 2, referralMult: 1.06 },
    icon: '💻',
  },
  {
    id: 'up_ehr_software',
    name: 'Practice Records System',
    blurb: 'Notes that fill themselves in halfway. Ninety minutes of evening paperwork becomes twenty.',
    cost: 2200,
    category: 'tech',
    requires: { minPracticeLevel: 3 },
    mods: { capacity: 1, quality: 0.02, moraleDrift: 0.4 },
    icon: '🗂️',
  },

  // ── Certification ─────────────────────────────────────────────────────────
  {
    id: 'up_couples_certification',
    name: 'Couples Certification',
    blurb: 'Formal training in holding two people and the third thing sitting between them.',
    cost: 2000,
    category: 'certification',
    requires: { minPracticeLevel: 2 },
    mods: { referralMult: 1.06, unlockSessionType: 'couples' },
    icon: '💞',
  },
  {
    id: 'up_family_certification',
    name: 'Family Systems Certification',
    blurb: 'Whole households in one room, and the nerve to arrange the chairs before they arrive.',
    cost: 3000,
    category: 'certification',
    requires: { minPracticeLevel: 3, hasUpgrade: ['up_couples_certification'] },
    mods: { referralMult: 1.08, unlockSessionType: 'family' },
    icon: '👪',
  },
  {
    id: 'up_child_certification',
    name: 'Child & Adolescent Certification',
    blurb: 'Play therapy training, consent paperwork for minors, and a rug you are allowed to sit on.',
    cost: 3600,
    category: 'certification',
    requires: { minPracticeLevel: 3, minCommunityTrust: 30 },
    mods: { referralMult: 1.1, quality: 0.01, unlockFeature: 'minors' },
    icon: '🧸',
  },
  {
    id: 'up_peer_consultation',
    name: 'Peer Consultation Retainer',
    blurb: 'An outside consultant on Thursday mornings. Stuck cases, said out loud, without shame.',
    cost: 4000,
    category: 'certification',
    requires: { minPracticeLevel: 4, minTherapists: 3 },
    mods: { quality: 0.03, moraleDrift: 0.8 },
    icon: '🗣️',
  },
  {
    id: 'up_trauma_certification',
    name: 'Trauma-Informed Certification',
    blurb: 'Phase-based training for the whole team. Stabilise first — and now everyone can say why.',
    cost: 4500,
    category: 'certification',
    requires: { minPracticeLevel: 4, minReputation: 35 },
    mods: { quality: 0.04, referralMult: 1.08 },
    icon: '🧭',
  },
  {
    id: 'up_dbt_team_certification',
    name: 'DBT Consultation Team',
    blurb: 'Weekly, non-optional, in the model’s own words: the therapy that keeps the therapists afloat.',
    cost: 5200,
    category: 'certification',
    requires: { minPracticeLevel: 5, minTherapists: 3 },
    mods: { quality: 0.04, moraleDrift: 0.7 },
    icon: '⚖️',
  },
  {
    id: 'up_crisis_certification',
    name: 'Crisis Response Certification',
    blurb: 'Risk assessment and safety planning, rehearsed until the worst call feels steady instead of loud.',
    cost: 6000,
    category: 'certification',
    requires: {
      minPracticeLevel: 5,
      minCommunityTrust: 45,
      hasUpgrade: ['up_supervision_room'],
    },
    mods: { quality: 0.02, referralMult: 1.05, moraleDrift: 0.3 },
    icon: '🆘',
  },

  // ── Automation ────────────────────────────────────────────────────────────
  {
    id: 'up_batch_booking',
    name: 'Batch Booking',
    blurb: 'Pick a client, drag across a week. Six recurring slots land in one gesture.',
    cost: 1500,
    category: 'automation',
    requires: { minPracticeLevel: 2 },
    mods: { unlockFeature: 'batch_booking' },
    icon: '🗓️',
  },
  {
    id: 'up_billing_service',
    name: 'Outside Billing Service',
    blurb: 'Someone else chases the claims now. Your clinicians go back to being clinicians.',
    cost: 2800,
    category: 'automation',
    requires: { minPracticeLevel: 3, hasUpgrade: ['up_ehr_software'] },
    mods: { moraleDrift: 0.6, energyRegenMult: 1.04 },
    icon: '🧾',
  },
  {
    id: 'up_intake_coordinator',
    name: 'Intake Coordinator',
    blurb: 'The phone answers in two rings and asks the right questions. Referrals stop quietly leaking away.',
    cost: 3400,
    category: 'automation',
    requires: { minPracticeLevel: 4, hasUpgrade: ['up_ehr_software'] },
    mods: { referralMult: 1.15, capacity: 2, moraleDrift: 0.3 },
    icon: '📋',
  },
  {
    id: 'up_auto_scheduler',
    name: 'Policy Auto-Scheduler',
    blurb: 'You write the rules — energy floors, who sees whom — and the week assembles itself overnight.',
    cost: 12000,
    category: 'automation',
    requires: { minPracticeLevel: 4, hasUpgrade: ['up_batch_booking'] },
    mods: { capacity: 2, energyRegenMult: 1.02, unlockFeature: 'auto_scheduler' },
    icon: '⚙️',
  },
];
